// Generated by CoffeeScript 1.6.1
var arm_down, arm_left, arm_right, arm_up, random_move_amount, random_speed;

$(function() {
  var body;
  body = $('body');
  return $(document).on('keyup', function(e) {
    switch (e.keyCode) {
      case 37:
        console.log('left');
        return arm_left();
      case 38:
        console.log('up');
        return arm_up();
      case 39:
        console.log('right');
        return arm_right();
      case 40:
        console.log('down');
        return arm_down();
    }
  });
});

random_move_amount = function() {
  return 100 + Math.random() * 50;
};

random_speed = function() {
  return Math.random() * 200;
};

arm_left = function() {
  var arm;
  arm = $('#arm');
  return arm.animate({
    left: "-=" + random_move_amount(),
    easing: 'linear',
    duration: random_speed()
  });
};

arm_right = function() {
  var arm;
  arm = $('#arm');
  return arm.animate({
    left: "+=" + random_move_amount(),
    easing: 'linear',
    duration: random_speed()
  });
};

arm_up = function() {
  var arm;
  arm = $('#arm');
  return arm.animate({
    top: "-=" + random_move_amount(),
    easing: 'linear',
    duration: random_speed()
  });
};

arm_down = function() {
  var arm;
  arm = $('#arm');
  return arm.animate({
    top: "+=" + random_move_amount(),
    easing: 'linear',
    duration: random_speed()
  });
};
